# main paths
data_path: "MNIST"
annotation_path: "MNIST"

# annotation paths
annotations: "train.csv"
images: "data"

# exp params
save_path: "Experiments/MNIST/baseline"
test_name: val

trainer:
  precision: 32
  accelerator: auto
  #  accelerator: gpu
  devices: auto
  #  devices: [0]

weights: "Experiments/MNIST/baseline/model.ckpt"
model:
  encoder: "tf_efficientnet_b0"
  output: 10

dataloader:
  batch_size: 128
  num_workers: 2

preprocess:
  side_size: 128
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

transforms:
